language: go

services:
  - docker

go:
  - "1.10.x"
  - master

script:
  - docker --version
  - go get -u github.com/golang/dep/cmd/dep && make vendor && make && make build
  - make build-multistage
