apiVersion: v1
name: goldpinger
appVersion: "3.10.2"
version: 1.0.1
description: Goldpinger is a tool to help debug, troubleshoot and visualize network connectivity and slowness issues.
home: https://github.com/bloomberg/goldpinger
sources:
  - https://github.com/bloomberg/goldpinger
